# Generated by Django 5.2.12 on 2026-03-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_prompts', '0004_testpromptexecution_remote_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpromptexecution',
            name='debug_file_checksum',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Checksum do arquivo de debug'),
        ),
        migrations.AddField(
            model_name='testpromptexecution',
            name='debug_file_content',
            field=models.BinaryField(blank=True, null=True, verbose_name='Conteudo binario do arquivo de debug'),
        ),
        migrations.AddField(
            model_name='testpromptexecution',
            name='debug_file_mime_type',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='MIME type do arquivo de debug'),
        ),
        migrations.AddField(
            model_name='testpromptexecution',
            name='debug_file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do arquivo de debug'),
        ),
        migrations.AddField(
            model_name='testpromptexecution',
            name='debug_file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Tamanho do arquivo de debug'),
        ),
        migrations.AlterField(
            model_name='testprompt',
            name='automation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID da automacao de teste selecionada'),
        ),
        migrations.AlterField(
            model_name='testpromptexecution',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('pending', 'Pendente'), ('running', 'Em andamento'), ('processing', 'Processando'), ('completed', 'Concluida'), ('failed', 'Falhou')], max_length=20, verbose_name='Status'),
        ),
    ]
