# Generated by Django 4.2.16 on 2026-03-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastAPIIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(max_length=500, verbose_name='Base URL FastAPI')),
                ('integration_token', models.TextField(blank=True, verbose_name='Token de integracao')),
                ('token_name', models.CharField(blank=True, max_length=120, verbose_name='Nome do token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima validacao em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuracao FastAPI',
                'verbose_name_plural': 'Configuracoes FastAPI',
            },
        ),
    ]
