# Generated by Django 5.2.12 on 2026-03-19 00:00

from django.db import migrations, models
import django.db.models.deletion


def migrate_legacy_token_to_table(apps, schema_editor):
    FastAPIIntegrationConfig = apps.get_model("core", "FastAPIIntegrationConfig")
    FastAPIIntegrationToken = apps.get_model("core", "FastAPIIntegrationToken")

    for config in FastAPIIntegrationConfig.objects.all():
        legacy_token = str(getattr(config, "integration_token", "") or "").strip()
        if not legacy_token:
            continue

        legacy_name = str(getattr(config, "token_name", "") or "").strip() or "token-principal"
        token = FastAPIIntegrationToken.objects.create(
            config_id=config.id,
            name=legacy_name[:120],
            integration_token=legacy_token,
            is_active=True,
        )
        config.selected_integration_token_id = token.id
        config.save(update_fields=["selected_integration_token"])


def restore_legacy_token_from_table(apps, schema_editor):
    FastAPIIntegrationConfig = apps.get_model("core", "FastAPIIntegrationConfig")
    FastAPIIntegrationToken = apps.get_model("core", "FastAPIIntegrationToken")

    for config in FastAPIIntegrationConfig.objects.all():
        token = None
        selected_token_id = getattr(config, "selected_integration_token_id", None)
        if selected_token_id:
            token = FastAPIIntegrationToken.objects.filter(id=selected_token_id).first()

        if token is None:
            token = FastAPIIntegrationToken.objects.filter(config_id=config.id).order_by("-updated_at", "-id").first()

        if token is None:
            config.token_name = ""
            config.integration_token = ""
        else:
            config.token_name = str(token.name or "")[:120]
            config.integration_token = str(token.integration_token or "")

        config.save(update_fields=["token_name", "integration_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FastAPIIntegrationToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                ("integration_token", models.TextField(verbose_name="Token de integracao")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_tokens",
                        to="core.fastapiintegrationconfig",
                        verbose_name="Configuracao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Integracao FastAPI",
                "verbose_name_plural": "Tokens de Integracao FastAPI",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="fastapiintegrationconfig",
            name="selected_integration_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.fastapiintegrationtoken",
                verbose_name="Token selecionado",
            ),
        ),
        migrations.RunPython(
            migrate_legacy_token_to_table,
            restore_legacy_token_from_table,
        ),
        migrations.RemoveField(
            model_name="fastapiintegrationconfig",
            name="integration_token",
        ),
        migrations.RemoveField(
            model_name="fastapiintegrationconfig",
            name="token_name",
        ),
    ]
