# Generated by Django 5.2.12 on 2026-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_fastapiintegrationtoken_and_config_refactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="fastapiintegrationtoken",
            name="external_token_id",
            field=models.UUIDField(
                blank=True,
                null=True,
                verbose_name="ID externo na FastAPI",
            ),
        ),
    ]
