# Generated by Django 4.2.16 on 2026-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='fastapi_provider_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID do provider na FastAPI'),
        ),
    ]
