# Generated by Django 5.2.12 on 2026-03-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testautomation',
            name='output_schema',
            field=models.JSONField(blank=True, null=True, verbose_name='Schema de saida'),
        ),
        migrations.AddField(
            model_name='testautomation',
            name='output_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Tipo de saida'),
        ),
        migrations.AddField(
            model_name='testautomation',
            name='result_formatter',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Formatador de resultado'),
        ),
        migrations.AddField(
            model_name='testautomation',
            name='result_parser',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Parser de resultado'),
        ),
    ]
