# Generated by Django 5.2.12 on 2026-03-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_automations', '0002_testautomation_output_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testautomation',
            name='debug_enabled',
            field=models.BooleanField(default=False, verbose_name='Modo debug da automacao'),
        ),
    ]
