# Generated by Django 4.2.16 on 2026-03-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('api_key', models.TextField(verbose_name='API key')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='Configuracao JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='providers.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciais',
                'ordering': ['provider__name', 'name'],
            },
        ),
    ]
