# Generated by Django 4.2.16 on 2026-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercredential',
            name='fastapi_credential_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID da credencial na FastAPI'),
        ),
    ]
