# Generated by Django 4.2.16 on 2026-03-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_catalog', '0002_providermodel_fastapi_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_prompts', to='models_catalog.providermodel', verbose_name='Modelo de IA')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['-updated_at', 'title'],
            },
        ),
    ]
