# Generated by Django 4.2.16 on 2026-03-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=160, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('context_window', models.PositiveIntegerField(blank=True, null=True, verbose_name='Janela de contexto')),
                ('input_cost_per_1k', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Custo input por 1k')),
                ('output_cost_per_1k', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Custo output por 1k')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_models', to='providers.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['provider__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='providermodel',
            constraint=models.UniqueConstraint(fields=('provider', 'slug'), name='uq_provider_model_provider_slug'),
        ),
    ]
